/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    orders: Order;
    invoices: Invoice;
    products: Product;
    categories: Category;
    'discount-codes': DiscountCode;
    'import-jobs': ImportJob;
    'gift-cards': GiftCard;
    'gift-card-transactions': GiftCardTransaction;
    customers: Customer;
    campaigns: Campaign;
    contacts: Contact;
    'marketing-configs': MarketingConfig;
    pages: Page;
    media: Media;
    'store-settings': StoreSetting;
    'section-definitions': SectionDefinition;
    users: User;
    'import-items': ImportItem;
    'gateway-configs': GatewayConfig;
    'payment-attempts': PaymentAttempt;
    'processed-webhook-events': ProcessedWebhookEvent;
    'payment-gateway-requests': PaymentGatewayRequest;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    orders: OrdersSelect<false> | OrdersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'gift-cards': GiftCardsSelect<false> | GiftCardsSelect<true>;
    'gift-card-transactions': GiftCardTransactionsSelect<false> | GiftCardTransactionsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    'marketing-configs': MarketingConfigsSelect<false> | MarketingConfigsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
    'section-definitions': SectionDefinitionsSelect<false> | SectionDefinitionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'import-items': ImportItemsSelect<false> | ImportItemsSelect<true>;
    'gateway-configs': GatewayConfigsSelect<false> | GatewayConfigsSelect<true>;
    'payment-attempts': PaymentAttemptsSelect<false> | PaymentAttemptsSelect<true>;
    'processed-webhook-events': ProcessedWebhookEventsSelect<false> | ProcessedWebhookEventsSelect<true>;
    'payment-gateway-requests': PaymentGatewayRequestsSelect<false> | PaymentGatewayRequestsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Human-readable order reference (e.g. ORD-00123).
   */
  orderNumber?: string | null;
  /**
   * Linked customer record. Optional — guest checkout is supported.
   */
  customer?: (number | null) | Customer;
  /**
   * Buyer's email at time of order (snapshot).
   */
  email: string;
  /**
   * Product snapshot at time of purchase.
   */
  lineItems: {
    productId: string;
    title: string;
    variantTitle?: string | null;
    unitPrice: number;
    qty: number;
    lineTotal: number;
    isGiftCard?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Amount in minor units (e.g. paise/cents). 1000 = ₹10.00
   */
  subtotal: number;
  /**
   * Amount in minor units (e.g. paise/cents). 1000 = ₹10.00
   */
  discountAmount: number;
  /**
   * Amount in minor units (e.g. paise/cents). 1000 = ₹10.00
   */
  shippingAmount: number;
  /**
   * Amount in minor units (e.g. paise/cents). 1000 = ₹10.00
   */
  taxAmount: number;
  /**
   * The VAT rate (%) in force when this order was placed.
   */
  taxRate?: number | null;
  /**
   * Whether the line prices already contained the tax. Decides whether the invoice shows the VAT as extracted from the total or added to it.
   */
  taxInclusive?: boolean | null;
  /**
   * The store’s tax registration number at the time of the order. Its presence is what makes this a tax invoice rather than a plain one.
   */
  supplierTrn?: string | null;
  /**
   * Amount in minor units (e.g. paise/cents). 1000 = ₹10.00
   */
  total: number;
  /**
   * Amount in minor units (e.g. paise/cents). 1000 = ₹10.00
   */
  giftCardAmount?: number | null;
  /**
   * One card per order in this version.
   */
  giftCardUsed?: (number | null) | GiftCard;
  giftCardRecipientName?: string | null;
  giftCardRecipientEmail?: string | null;
  giftCardMessage?: string | null;
  /**
   * Total refunded against this order, in minor units. Netted off revenue while the order still stands; a FULL refund moves the status to Refunded, which removes it from revenue entirely.
   */
  refundedAmount?: number | null;
  /**
   * Discount code applied to this order (if any).
   */
  discountCode?: string | null;
  /**
   * 3-letter ISO 4217 currency code, e.g. INR, USD.
   */
  currency: string;
  shippingAddress: {
    name: string;
    line1: string;
    line2?: string | null;
    city: string;
    state?: string | null;
    postalCode: string;
    country: string;
    phone?: string | null;
  };
  /**
   * Pickup/delivery selection captured at checkout (snapshot).
   */
  fulfillment?: {
    method?: ('shipping' | 'pickup' | 'delivery') | null;
    /**
     * Scheduled collection/delivery day.
     */
    date?: string | null;
    /**
     * e.g. "07:00–09:00".
     */
    windowLabel?: string | null;
    /**
     * Delivery zone (delivery only).
     */
    zoneName?: string | null;
  };
  status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  /**
   * e.g. razorpay, stripe.
   */
  paymentProvider?: string | null;
  /**
   * Provider's payment or order ID.
   */
  providerRef?: string | null;
  /**
   * Webhook event ID for idempotency — store on receipt to avoid double-processing.
   */
  providerEventId?: string | null;
  /**
   * Timestamp when payment was confirmed (UTC).
   */
  paidAt?: string | null;
  /**
   * Set when a payment was AUTHORIZED but not yet captured (e.g. manual-capture). The order is NOT paid or fulfilled in this state — needs merchant/provider capture.
   */
  authorizedAt?: string | null;
  /**
   * The payment attempt that (last) drove this order.
   */
  paymentAttempt?: (number | null) | PaymentAttempt;
  /**
   * Carrier tracking number — visible to the customer.
   */
  trackingNumber?: string | null;
  /**
   * Assigned when the invoice is issued.
   */
  invoiceNumber?: string | null;
  invoiceIssuedAt?: string | null;
  invoiceSentAt?: string | null;
  /**
   * Generated invoice PDF.
   */
  invoicePdf?: (number | null) | Invoice;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer records scoped per tenant. NOT auth-enabled — login is handled separately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  /**
   * Customer's full name.
   */
  name?: string | null;
  /**
   * Saved shipping/billing addresses.
   */
  addresses?:
    | {
        line1: string;
        line2?: string | null;
        city: string;
        state?: string | null;
        postalCode: string;
        country: string;
        id?: string | null;
      }[]
    | null;
  /**
   * scrypt hash — never exposed via API.
   */
  passwordHash?: string | null;
  /**
   * Rotating nonce for single-use magic-link tokens — never exposed.
   */
  magicLinkNonce?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Issued gift cards. Codes are never shown — only the last four characters.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards".
 */
export interface GiftCard {
  id: number;
  codeHash: string;
  last4: string;
  /**
   * Face value in minor units (e.g. fils/paise).
   */
  initialAmount: number;
  /**
   * Remaining balance in minor units. Derived from the ledger.
   */
  balance: number;
  /**
   * Snapshotted at issue so a store currency change cannot revalue this card.
   */
  currency: string;
  /**
   * Void blocks redemption. A zero balance is NOT void — a refund can restore it.
   */
  status: 'active' | 'void';
  issuedFromOrder?: (number | null) | Order;
  recipientName?: string | null;
  recipientEmail?: string | null;
  message?: string | null;
  issuedAt?: string | null;
  /**
   * Always empty. Cards do not expire in this version; the field exists so adding expiry later is a behaviour change, not a migration.
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts".
 */
export interface PaymentAttempt {
  id: number;
  order: number | Order;
  /**
   * Registry provider slug (e.g. stripe, razorpay, offline).
   */
  provider: string;
  /**
   * Provider's session/link id (cs_… / plink_…). Our lookup key.
   */
  providerSessionId?: string | null;
  /**
   * Our idempotency key for this attempt.
   */
  idempotencyKey: string;
  status: 'created' | 'redirected' | 'pending' | 'authorized' | 'succeeded' | 'failed' | 'cancelled' | 'expired';
  /**
   * Amount in minor units (e.g. paise/cents).
   */
  amount?: number | null;
  /**
   * 3-letter ISO 4217 code.
   */
  currency?: string | null;
  /**
   * Provider's payment id (pay_… / pi_…) once known.
   */
  providerPaymentId?: string | null;
  failureCode?: string | null;
  failureMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  /**
   * Allocated by issueInvoice. Also stored on the order.
   */
  invoiceNumber?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | Media)[] | null;
  category?: (number | null) | Category;
  /**
   * Created by the sample catalogue seeder.
   */
  isSampleContent?: boolean | null;
  /**
   * When on, paying for this product issues a gift card per unit. Each variant price is the card’s face value. Gift-card products are never taxed — the tax is charged when the card is spent.
   */
  issuesGiftCard?: boolean | null;
  /**
   * URL-safe, unique within this store. Lowercase letters, numbers, hyphens.
   */
  slug: string;
  status: 'draft' | 'active';
  /**
   * Price customers pay. Stored in minor units; enter a normal amount above.
   */
  price: number;
  /**
   * How many you have. 0 shows this product as “Out of stock” on your storefront. Ignored for gift cards — they are generated on demand and never run out.
   */
  stock: number;
  /**
   * Variant axes, e.g. Size with values S/M/L.
   */
  options?:
    | {
        /**
         * e.g. "Size"
         */
        name: string;
        values: {
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Each variant has its own price, stock and SKU.
   */
  variants?:
    | {
        /**
         * Auto-filled from the selected options when this product defines options; otherwise enter a label like "M / Red".
         */
        title?: string | null;
        /**
         * Which option value this variant is, per axis.
         */
        optionValues?:
          | {
              option: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Price customers pay. Stored in minor units; enter a normal amount above.
         */
        price: number;
        sku?: string | null;
        stock: number;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        /**
         * e.g. "Material"
         */
        label: string;
        /**
         * e.g. "Organic cotton"
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Set by the product importer. Absent on products created by hand.
   */
  importedFrom?: {
    sourceId?: string | null;
    sourceOrigin?: string | null;
    externalId?: string | null;
    importedAt?: string | null;
    priceTaxTreatment?: ('inclusive' | 'exclusive') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Set by the product importer to avoid re-uploading identical files.
   */
  contentHash?: string | null;
  alt: string;
  /**
   * Created by the sample catalogue seeder.
   */
  isSampleContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL-safe, unique within this store. Lowercase letters, numbers, hyphens.
   */
  slug: string;
  description?: string | null;
  /**
   * Optional. Used by the Category Previews storefront block.
   */
  image?: (number | null) | Media;
  /**
   * Created by the sample catalogue seeder.
   */
  isSampleContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  type: 'percent' | 'fixed';
  /**
   * For percent: whole percentage (e.g. 10 = 10%). For fixed: minor units (e.g. 500 = ₹5.00).
   */
  value: number;
  /**
   * Minimum subtotal (minor units) required to use this code.
   */
  minOrder?: number | null;
  /**
   * Maximum total uses. Leave blank for unlimited.
   */
  usageLimit?: number | null;
  /**
   * Automatically incremented on each successful use.
   */
  usedCount: number;
  /**
   * Code becomes active at this date/time (UTC). Leave blank for no start restriction.
   */
  validFrom?: string | null;
  /**
   * Code expires after this date/time (UTC). Leave blank for no expiry.
   */
  validUntil?: string | null;
  /**
   * Uncheck to disable without deleting.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product imports from an existing Shopify or WooCommerce store.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  /**
   * The storefront address the merchant pasted.
   */
  sourceUrl: string;
  /**
   * Which adapter matched, as a registry id. Set by detection — the value is data, and nothing outside the adapter and the registry may branch on it.
   */
  sourceId?: string | null;
  status: 'detecting' | 'ready' | 'importing' | 'completed' | 'failed' | 'cancelled';
  detectedProductCount?: number | null;
  selectedCount?: number | null;
  importedCount?: number | null;
  failedCount?: number | null;
  /**
   * ISO 4217 as reported by the source. WooCommerce declares one; Shopify never does, in which case prices are read as the store's own currency.
   */
  sourceCurrency?: string | null;
  /**
   * How the source store priced its products. Required before import; deliberately has no default. Snapshotted onto each imported product so it can be reconciled when storefront tax is calculated.
   */
  priceTaxTreatment?: ('inclusive' | 'exclusive') | null;
  ownershipAttestedAt?: string | null;
  ownershipAttestedBy?: (number | null) | User;
  /**
   * Why the run failed, in the words the merchant should see.
   */
  error?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: 'super-admin'[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-card-transactions".
 */
export interface GiftCardTransaction {
  id: number;
  giftCard: number | GiftCard;
  type: 'issue' | 'redeem' | 'reverse';
  /**
   * Always positive, in minor units. `type` carries the direction.
   */
  amount: number;
  order?: (number | null) | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  name: string;
  subject: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  audience?: {
    mode?: ('all' | 'tag' | 'source') | null;
    tag?: string | null;
    source?: ('checkout' | 'newsletter' | 'import' | 'manual') | null;
  };
  /**
   * Set to 'sending' to launch immediately, or set to 'scheduled' and fill in scheduledAt to send later. Counters (totalRecipients, sentCount, failedCount) update automatically — do not edit them directly.
   */
  status?: ('draft' | 'scheduled' | 'sending' | 'sent' | 'failed') | null;
  scheduledAt?: string | null;
  totalRecipients?: number | null;
  sentCount?: number | null;
  failedCount?: number | null;
  sendCursor?: number | null;
  /**
   * Counts consecutive failed send chunks. Campaign is marked failed after 20.
   */
  sendAttempts?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  email: string;
  name?: string | null;
  tags?: string[] | null;
  status?: ('subscribed' | 'unsubscribed') | null;
  source?: ('checkout' | 'newsletter' | 'import' | 'manual') | null;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-configs".
 */
export interface MarketingConfig {
  id: number;
  /**
   * Paste your payment-gateway secret key here. For Stripe, use a restricted key starting with `rk_` (not your live secret key). The value is encrypted at rest and will be masked after saving — paste a new value to rotate the key.
   */
  resendApiKey?: string | null;
  fromName?: string | null;
  /**
   * Must be a verified sender/domain in your Resend account
   */
  fromEmail: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe, unique within this store. Lowercase letters, numbers, hyphens.
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | ProductGridBlock
        | ImageGalleryBlock
        | CTABannerBlock
        | TestimonialsBlock
        | FAQBlock
        | NewsletterSignupBlock
        | SplitHeroBlock
        | SpacerBlock
        | FeatureGridBlock
        | StepsBlock
        | LogoStripBlock
        | VideoEmbedBlock
        | ContactBlock
        | FeaturedProductBlock
        | IncentivesBlock
        | CategoryPreviewsBlock
        | PromoSectionBlock
        | ReviewsBlock
        | MediaHeroBlock
        | TickerBlock
        | StoryStatsBlock
        | {
            /**
             * Which of your saved sections to show here.
             */
            definition: number | SectionDefinition;
            /**
             * Colour band for this placement. Left blank, it is filled in from the section’s own default when you save.
             */
            scheme?: ('' | 'default' | 'muted' | 'inverse' | 'accent') | null;
            /**
             * The words and pictures for this placement.
             */
            content?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'customSection';
          }
      )[]
    | null;
  meta?: {
    /**
     * Overrides the browser tab and search-result title. Leave blank to use the page title. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description shown in search results and social shares. ~155 characters.
     */
    description?: string | null;
    /**
     * Social share image (Open Graph / Twitter). Recommended 1200×630.
     */
    image?: (number | null) | Media;
    /**
     * Canonical URL override for duplicate-content control. Leave blank to use this page’s own URL.
     */
    canonicalUrl?: string | null;
  };
  /**
   * Hide this page from search engines and AI crawlers (robots: noindex, nofollow).
   */
  noindex?: boolean | null;
  /**
   * Help AI answer engines (ChatGPT, Perplexity, Google AI Overviews) understand and quote this page.
   */
  aeo?: {
    /**
     * A direct 1–2 sentence answer/summary AI engines can quote. Feeds the page’s structured-data description.
     */
    answerSummary?: string | null;
    /**
     * Primary schema.org type emitted as JSON-LD. FAQ blocks additionally emit FAQPage automatically.
     */
    schemaType?: ('WebPage' | 'Article') | null;
  };
  /**
   * Created by the sample catalogue seeder.
   */
  isSampleContent?: boolean | null;
  blockStyles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant: 'centered' | 'split' | 'overlay' | 'video' | 'stacked' | 'showcase';
  /**
   * Colour band for this hero. Blank = the store theme’s default.
   */
  scheme?: ('' | 'default' | 'muted' | 'inverse' | 'accent') | null;
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional second line, shown in the accent colour (two-tone heading).
   */
  headingAccent?: string | null;
  subheading?: string | null;
  /**
   * Small trust chip under the text, e.g. “Gluten & dairy free”.
   */
  featureChip?: string | null;
  /**
   * Image OR video (mp4/webm). Used by every variant except plain Centered, which can also use the legacy background image below.
   */
  media?: (number | null) | Media;
  /**
   * Fallback frame shown while a background video loads.
   */
  poster?: (number | null) | Media;
  mediaSide?: ('left' | 'right') | null;
  textAlign?: ('left' | 'center' | 'right') | null;
  /**
   * Vertical position of the text over the media.
   */
  verticalAlign?: ('top' | 'middle' | 'bottom') | null;
  /**
   * Darkening scrim over the media so text stays legible.
   */
  overlay?: ('none' | 'light' | 'medium' | 'dark') | null;
  /**
   * Minimum height of the hero. “Auto” keeps this layout’s natural height.
   */
  minHeight?: ('auto' | 'md' | 'lg' | 'half' | 'threeQuarter' | 'screen') | null;
  primaryCtaLabel?: string | null;
  /**
   * e.g. /products
   */
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  /**
   * Up to two info cards pinned over the media.
   */
  floatingCards?:
    | {
        title: string;
        subtitle?: string | null;
        corner?: ('topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight') | null;
        id?: string | null;
      }[]
    | null;
  backgroundImage?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * e.g. /products
   */
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock".
 */
export interface ProductGridBlock {
  variant?: ('grid' | 'carousel' | 'list') | null;
  /**
   * Columns for the Grid variant.
   */
  columns?: ('2' | '3' | '4') | null;
  /**
   * Small kicker above the heading, e.g. "At the bench today".
   */
  eyebrow?: string | null;
  heading?: string | null;
  source: 'latest' | 'category' | 'manual';
  /**
   * Show products from this category
   */
  category?: (number | null) | Category;
  /**
   * Manually choose products to display
   */
  products?: (number | Product)[] | null;
  /**
   * Max products to show (ignored for manual selection)
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  images: (number | Media)[];
  columns?: ('2' | '3' | '4') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock".
 */
export interface CTABannerBlock {
  heading: string;
  body?: string | null;
  buttonLabel?: string | null;
  /**
   * e.g. /products or https://example.com
   */
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  items?:
    | {
        quote: string;
        author: string;
        /**
         * Optional — e.g. "CEO at Acme"
         */
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock".
 */
export interface NewsletterSignupBlock {
  heading?: string | null;
  /**
   * Placeholder text for the email input
   */
  placeholder?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitHeroBlock".
 */
export interface SplitHeroBlock {
  variant: 'mediaLeft' | 'mediaRight' | 'overlay' | 'stacked';
  /**
   * How the text and buttons are aligned.
   */
  textAlign?: ('left' | 'center' | 'right') | null;
  /**
   * Vertical position of the text over the image.
   */
  overlayVerticalAlign?: ('top' | 'middle' | 'bottom') | null;
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  media?: (number | null) | Media;
  primaryCtaLabel?: string | null;
  /**
   * e.g. /products
   */
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'splitHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  variant: 'blank' | 'line' | 'dots' | 'gradient';
  size: 'sm' | 'md' | 'lg' | 'xl';
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  variant: 'iconTop' | 'iconLeft' | 'cards' | 'minimal';
  heading?: string | null;
  columns: '2' | '3' | '4';
  items?:
    | {
        icon: 'truck' | 'leaf' | 'clock' | 'star' | 'shield' | 'heart';
        heading: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  variant: 'horizontal' | 'vertical' | 'cards' | 'compact';
  heading?: string | null;
  numbered?: boolean | null;
  steps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock".
 */
export interface LogoStripBlock {
  variant: 'staticRow' | 'grid' | 'marquee' | 'bordered';
  heading?: string | null;
  grayscale?: boolean | null;
  logos?:
    | {
        image: number | Media;
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  variant: 'contained' | 'fullBleed' | 'sideBySide' | 'textOverlay';
  heading?: string | null;
  /**
   * Paste a YouTube or Vimeo URL. Niblr does not host video: there is no transcoding, no adaptive bitrate and no poster generation, so a 1080p upload stalls for shoppers on slow connections. YouTube and Vimeo do all three for free, and better.
   */
  provider: 'youtube' | 'vimeo';
  /**
   * Paste the video page URL
   */
  url?: string | null;
  poster?: (number | null) | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  variant: 'mapSplit' | 'mapStacked' | 'detailsOnly' | 'banner';
  heading?: string | null;
  address?: string | null;
  hours?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  /**
   * Number in international format, e.g. 971500000000
   */
  whatsapp?: string | null;
  email?: string | null;
  /**
   * Google Maps > Share > Embed a map > copy the src URL. Only a Google Maps embed URL renders here — anything else, or an invalid URL, shows as a blank frame.
   */
  mapEmbedUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductBlock".
 */
export interface FeaturedProductBlock {
  variant: 'imageLeft' | 'imageRight' | 'overlay' | 'stacked';
  product: number | Product;
  headingOverride?: string | null;
  ctaLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProduct';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IncentivesBlock".
 */
export interface IncentivesBlock {
  heading?: string | null;
  columns: '2' | '3' | '4';
  items?:
    | {
        icon: 'truck' | 'returns' | 'lock' | 'support' | 'badge' | 'gift';
        heading: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'incentives';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryPreviewsBlock".
 */
export interface CategoryPreviewsBlock {
  variant: 'grid' | 'overlayCards' | 'list';
  heading?: string | null;
  source: 'all' | 'manual';
  /**
   * Choose and order the categories to display.
   */
  categories?: (number | Category)[] | null;
  /**
   * Max categories to show (ignored for manual selection).
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryPreviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoSectionBlock".
 */
export interface PromoSectionBlock {
  variant: 'splitImage' | 'overlay' | 'bannerStrip';
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  /**
   * Used by Split image and Full-bleed overlay.
   */
  media?: (number | null) | Media;
  primaryCtaLabel?: string | null;
  /**
   * e.g. /products
   */
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock".
 */
export interface ReviewsBlock {
  variant: 'cards' | 'list' | 'masonry';
  heading?: string | null;
  items?:
    | {
        /**
         * Stars, 1–5.
         */
        rating: number;
        quote: string;
        author: string;
        /**
         * e.g. “Verified buyer”.
         */
        role?: string | null;
        /**
         * Optional — link this review to a product.
         */
        product?: (number | null) | Product;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaHeroBlock".
 */
export interface MediaHeroBlock {
  variant: 'split' | 'overlay';
  /**
   * Image OR video (mp4/webm). Video plays muted, looped, autoplay.
   */
  media?: (number | null) | Media;
  /**
   * Optional. Poster/fallback shown while a video loads.
   */
  poster?: (number | null) | Media;
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  textAlign?: ('left' | 'center' | 'right') | null;
  /**
   * Vertical position of the text over the media.
   */
  verticalAlign?: ('top' | 'middle' | 'bottom') | null;
  /**
   * Darkening scrim over the media so text stays legible.
   */
  overlay?: ('none' | 'light' | 'medium' | 'dark') | null;
  minHeight?: ('md' | 'lg' | 'screen') | null;
  primaryCtaLabel?: string | null;
  /**
   * e.g. /products
   */
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TickerBlock".
 */
export interface TickerBlock {
  variant: 'static' | 'marquee';
  /**
   * Character shown between phrases (e.g. · or —).
   */
  separator?: string | null;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ticker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoryStatsBlock".
 */
export interface StoryStatsBlock {
  variant: 'imageLeft' | 'imageRight';
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  image?: (number | null) | Media;
  stats?:
    | {
        /**
         * e.g. 24h, 4, 0
         */
        value: string;
        /**
         * e.g. Slow ferment
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'storyStats';
}
/**
 * Reusable section layouts. Pick a starting layout and fill in your own content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-definitions".
 */
export interface SectionDefinition {
  id: number;
  /**
   * What you will see when picking this section on a page.
   */
  name: string;
  /**
   * Pick a starting layout. You can change it before you publish.
   */
  recipe:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Which starting layout this section came from.
   */
  presetId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  storeName: string;
  currency: 'AED' | 'INR' | 'USD' | 'EUR' | 'GBP';
  logo?: (number | null) | Media;
  description?: string | null;
  theme?: {
    /**
     * Headings, links, and primary UI on your storefront.
     */
    primaryColor?: string | null;
    /**
     * Buttons and calls to action.
     */
    accentColor?: string | null;
    /**
     * Page background.
     */
    backgroundColor?: string | null;
    /**
     * Body text.
     */
    textColor?: string | null;
    /**
     * Font for body text and UI. Choose a Google Font, or your visitors’ system font.
     */
    fontFamily?: string | null;
    fontFamilyAxes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Optional secondary font for headings/display. Leave blank to use the template’s heading font.
     */
    headingFont?: string | null;
    headingFontAxes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Optional third font for accent text and eyebrows in block styles. Leave blank to use your heading font.
     */
    displayFont?: string | null;
    displayFontAxes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Font weight for headings. Leave blank to use the template default.
     */
    headingWeight?: ('300' | '400' | '500' | '600' | '700') | null;
    /**
     * Font weight for body text. Leave blank to use the template default.
     */
    bodyWeight?: ('300' | '400' | '500' | '600' | '700') | null;
    /**
     * Corner rounding on buttons. Leave as Theme default to follow your template.
     */
    buttonRadius?: ('' | 'none' | 'sm' | 'md' | 'lg' | 'full') | null;
  };
  themeCustomizations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  blockStyleDefaults?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * CSS for your storefront content pages, written against the published data-nb-* attributes. Growth plan. Not applied to the cart or checkout pages — though the cart drawer, which appears on content pages, is styled. @import, external URLs and position: fixed are removed on save. Full reference and worked selectors: https://niblr.store/docs/custom-css
   */
  customCss?: string | null;
  /**
   * Turn off to disable your custom CSS without deleting it.
   */
  customCssEnabled?: boolean | null;
  /**
   * Optional bar shown above the header, e.g. “Order before 9pm · Collect the next morning”.
   */
  announcement?: string | null;
  /**
   * Header navigation. Leave empty to use the defaults (Home, Products, Account).
   */
  navLinks?:
    | {
        label: string;
        /**
         * e.g. /products or /products?category=sweet-pastries
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How the header is arranged. “Theme default” keeps the layout your template ships with.
   */
  headerLayout?: ('theme' | 'standard' | 'centered' | 'editorial') | null;
  /**
   * Header logo size. Medium is the default.
   */
  logoSize?: ('small' | 'medium' | 'large' | 'xlarge') | null;
  /**
   * Pickup / local-delivery scheduling. When enabled, checkout asks the buyer to choose a method, date and time window.
   */
  fulfillment?: {
    enabled?: boolean | null;
    /**
     * IANA timezone the cutoff and windows are evaluated in.
     */
    timezone?: string | null;
    /**
     * HH:mm — orders placed before this collect/deliver next day; after it, the day after next.
     */
    cutoffTime?: string | null;
    /**
     * How many days ahead a buyer can schedule.
     */
    maxDaysAhead?: number | null;
    pickup?: {
      enabled?: boolean | null;
      /**
       * Shown to buyers, e.g. "SD Bakery, Jumeirah — Dubai".
       */
      locationLabel?: string | null;
      windows?:
        | {
            label: string;
            /**
             * HH:mm
             */
            start: string;
            /**
             * HH:mm
             */
            end: string;
            id?: string | null;
          }[]
        | null;
    };
    delivery?: {
      enabled?: boolean | null;
      zones?:
        | {
            name: string;
            areasNote?: string | null;
            /**
             * Delivery fee in minor units (e.g. 1000 = AED 10.00).
             */
            fee: number;
            id?: string | null;
          }[]
        | null;
      windows?:
        | {
            label: string;
            /**
             * HH:mm
             */
            start: string;
            /**
             * HH:mm
             */
            end: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  tax?: {
    /**
     * Off by default. While off, orders carry no tax and invoices show no VAT line at all — which is correct for an unregistered business.
     */
    enabled?: boolean | null;
    /**
     * Printed on every tax invoice. A UAE simplified tax invoice is not compliant without it, so "Tax Invoice" is only used as the heading once this is set.
     */
    registrationNumber?: string | null;
    /**
     * e.g. 5 for the UAE, 15 for Saudi Arabia.
     */
    rate?: number | null;
    /**
     * The norm in the UAE and India, and the default here. When on, a listed AED 100 stays AED 100 at checkout and the VAT is shown as the portion contained within it. When off, VAT is added on top and the shopper pays more than the listed price.
     */
    pricesIncludeTax?: boolean | null;
  };
  /**
   * Next sequential invoice number for this store.
   */
  nextInvoiceNumber?: number | null;
  /**
   * Analytics and marketing pixels. Each is an ID only — we render the official snippet for you. Leave blank to disable. For anything not listed, add it via your GTM container.
   */
  analytics?: {
    /**
     * e.g. G-XXXXXXXXXX — from GA Admin → Data Streams.
     */
    ga4MeasurementId?: string | null;
    /**
     * e.g. GTM-XXXXXX — use this to add any tag not listed below.
     */
    gtmContainerId?: string | null;
    /**
     * Numeric ID from Meta Events Manager (e.g. 123456789012345).
     */
    metaPixelId?: string | null;
    /**
     * From TikTok Ads → Events → Web Events (e.g. C1A2B3...).
     */
    tiktokPixelId?: string | null;
    /**
     * From Pinterest Ads → Conversions (numeric tag ID).
     */
    pinterestTagId?: string | null;
    /**
     * The UUID from Snapchat Ads → Events Manager.
     */
    snapchatPixelId?: string | null;
    /**
     * e.g. AW-123456789 — from Google Ads → Conversions.
     */
    googleAdsId?: string | null;
    /**
     * From clarity.microsoft.com → Settings (free heatmaps/recordings).
     */
    clarityProjectId?: string | null;
    /**
     * Numeric Site ID from your Hotjar account.
     */
    hotjarId?: string | null;
  };
  /**
   * Storefront theme id. Pick one from the theme gallery on the storefront.
   */
  storefrontTheme?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-items".
 */
export interface ImportItem {
  id: number;
  job: number | ImportJob;
  /**
   * The product's stable id on the source platform.
   */
  externalId: string;
  /**
   * The normalised SourceProduct the import phase will write. There was a `raw` field beside this holding "the source payload as received" — it was a byte-identical copy of this one, because adapters only ever return the mapped product. It doubled the database cost of every import and was removed 4 Aug 2026. Storing the true source payload would mean an adapter actually returning it.
   */
  mapped?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'selected' | 'skipped' | 'imported' | 'failed';
  /**
   * Stable codes the review grid renders as chips.
   */
  warnings?:
    | (
        | 'no_price'
        | 'no_images'
        | 'many_variants'
        | 'currency_mismatch'
        | 'boilerplate_description'
        | 'variants_unavailable'
        | 'duplicate_sku'
        | 'inventory_unknown'
      )[]
    | null;
  /**
   * Set when a tick takes this item. Two concurrent ticks cannot claim the same row, so a merchant refreshing the import screen cannot double-create a product.
   */
  claimedAt?: string | null;
  error?: string | null;
  /**
   * Set once this item has been imported.
   */
  product?: (number | null) | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment provider configurations. Manage these from Settings → Payments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gateway-configs".
 */
export interface GatewayConfig {
  id: number;
  /**
   * Registry provider slug (e.g. stripe, razorpay, offline, mollie, paystack). Managed from Settings → Payments; adding a provider needs no schema change.
   */
  provider: string;
  /**
   * Offer this provider at checkout when its configuration is valid.
   */
  enabled?: boolean | null;
  /**
   * Which set of provider credentials this configuration represents.
   */
  environment?: ('test' | 'live') | null;
  encryptedCredentials?: string | null;
  /**
   * Bumped on each credential rotation (for future key rotation).
   */
  configurationVersion?: number | null;
  /**
   * Legacy public/publishable key. Superseded by the encrypted credential blob.
   */
  publishableKey?: string | null;
  /**
   * Paste your payment-gateway secret key here. For Stripe, use a restricted key starting with `rk_` (not your live secret key). The value is encrypted at rest and will be masked after saving — paste a new value to rotate the key.
   */
  secretKey?: string | null;
  /**
   * Paste your payment-gateway secret key here. For Stripe, use a restricted key starting with `rk_` (not your live secret key). The value is encrypted at rest and will be masked after saving — paste a new value to rotate the key.
   */
  webhookSecret?: string | null;
  /**
   * Legacy single-active flag. Superseded by `enabled`.
   */
  active?: boolean | null;
  /**
   * Informational only. Register in your provider dashboard: https://<your-store-domain>/api/webhooks/<provider>/<tenant-slug>
   */
  webhookUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processed-webhook-events".
 */
export interface ProcessedWebhookEvent {
  id: number;
  provider: string;
  /**
   * Provider's unique webhook event id.
   */
  providerEventId: string;
  paymentAttempt?: (number | null) | PaymentAttempt;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-gateway-requests".
 */
export interface PaymentGatewayRequest {
  id: number;
  /**
   * The payment provider the merchant would like added.
   */
  providerName: string;
  /**
   * Optional context (country, why they need it, volume).
   */
  note?: string | null;
  /**
   * Email of the admin who submitted the request.
   */
  requestedByEmail?: string | null;
  /**
   * Platform triage status.
   */
  status?: ('new' | 'reviewing' | 'planned' | 'declined') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  products?: {
    /**
     * Allow clients to find products.
     */
    find?: boolean | null;
    /**
     * Allow clients to create products.
     */
    create?: boolean | null;
    /**
     * Allow clients to update products.
     */
    update?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
  };
  orders?: {
    /**
     * Allow clients to find orders.
     */
    find?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * List the storefront page-builder blocks available for composing a page layout. Returns each block's slug, fields (name/type/required), whether it is a premium block, and whether this store's plan can use it (`available`). Call this before creating or updating a page.
     */
    listBlocks?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'gift-cards';
        value: number | GiftCard;
      } | null)
    | ({
        relationTo: 'gift-card-transactions';
        value: number | GiftCardTransaction;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'marketing-configs';
        value: number | MarketingConfig;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'store-settings';
        value: number | StoreSetting;
      } | null)
    | ({
        relationTo: 'section-definitions';
        value: number | SectionDefinition;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'import-items';
        value: number | ImportItem;
      } | null)
    | ({
        relationTo: 'gateway-configs';
        value: number | GatewayConfig;
      } | null)
    | ({
        relationTo: 'payment-attempts';
        value: number | PaymentAttempt;
      } | null)
    | ({
        relationTo: 'processed-webhook-events';
        value: number | ProcessedWebhookEvent;
      } | null)
    | ({
        relationTo: 'payment-gateway-requests';
        value: number | PaymentGatewayRequest;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  email?: T;
  lineItems?:
    | T
    | {
        productId?: T;
        title?: T;
        variantTitle?: T;
        unitPrice?: T;
        qty?: T;
        lineTotal?: T;
        isGiftCard?: T;
        id?: T;
      };
  subtotal?: T;
  discountAmount?: T;
  shippingAmount?: T;
  taxAmount?: T;
  taxRate?: T;
  taxInclusive?: T;
  supplierTrn?: T;
  total?: T;
  giftCardAmount?: T;
  giftCardUsed?: T;
  giftCardRecipientName?: T;
  giftCardRecipientEmail?: T;
  giftCardMessage?: T;
  refundedAmount?: T;
  discountCode?: T;
  currency?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  fulfillment?:
    | T
    | {
        method?: T;
        date?: T;
        windowLabel?: T;
        zoneName?: T;
      };
  status?: T;
  paymentProvider?: T;
  providerRef?: T;
  providerEventId?: T;
  paidAt?: T;
  authorizedAt?: T;
  paymentAttempt?: T;
  trackingNumber?: T;
  invoiceNumber?: T;
  invoiceIssuedAt?: T;
  invoiceSentAt?: T;
  invoicePdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  images?: T;
  category?: T;
  isSampleContent?: T;
  issuesGiftCard?: T;
  slug?: T;
  status?: T;
  price?: T;
  stock?: T;
  options?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        title?: T;
        optionValues?:
          | T
          | {
              option?: T;
              value?: T;
              id?: T;
            };
        price?: T;
        sku?: T;
        stock?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  importedFrom?:
    | T
    | {
        sourceId?: T;
        sourceOrigin?: T;
        externalId?: T;
        importedAt?: T;
        priceTaxTreatment?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  isSampleContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  minOrder?: T;
  usageLimit?: T;
  usedCount?: T;
  validFrom?: T;
  validUntil?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  sourceUrl?: T;
  sourceId?: T;
  status?: T;
  detectedProductCount?: T;
  selectedCount?: T;
  importedCount?: T;
  failedCount?: T;
  sourceCurrency?: T;
  priceTaxTreatment?: T;
  ownershipAttestedAt?: T;
  ownershipAttestedBy?: T;
  error?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-cards_select".
 */
export interface GiftCardsSelect<T extends boolean = true> {
  codeHash?: T;
  last4?: T;
  initialAmount?: T;
  balance?: T;
  currency?: T;
  status?: T;
  issuedFromOrder?: T;
  recipientName?: T;
  recipientEmail?: T;
  message?: T;
  issuedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-card-transactions_select".
 */
export interface GiftCardTransactionsSelect<T extends boolean = true> {
  giftCard?: T;
  type?: T;
  amount?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  addresses?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        id?: T;
      };
  passwordHash?: T;
  magicLinkNonce?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  body?: T;
  audience?:
    | T
    | {
        mode?: T;
        tag?: T;
        source?: T;
      };
  status?: T;
  scheduledAt?: T;
  totalRecipients?: T;
  sentCount?: T;
  failedCount?: T;
  sendCursor?: T;
  sendAttempts?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  tags?: T;
  status?: T;
  source?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-configs_select".
 */
export interface MarketingConfigsSelect<T extends boolean = true> {
  resendApiKey?: T;
  fromName?: T;
  fromEmail?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        productGrid?: T | ProductGridBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        ctaBanner?: T | CTABannerBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        splitHero?: T | SplitHeroBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        logoStrip?: T | LogoStripBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        featuredProduct?: T | FeaturedProductBlockSelect<T>;
        incentives?: T | IncentivesBlockSelect<T>;
        categoryPreviews?: T | CategoryPreviewsBlockSelect<T>;
        promoSection?: T | PromoSectionBlockSelect<T>;
        reviews?: T | ReviewsBlockSelect<T>;
        mediaHero?: T | MediaHeroBlockSelect<T>;
        ticker?: T | TickerBlockSelect<T>;
        storyStats?: T | StoryStatsBlockSelect<T>;
        customSection?:
          | T
          | {
              definition?: T;
              scheme?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalUrl?: T;
      };
  noindex?: T;
  aeo?:
    | T
    | {
        answerSummary?: T;
        schemaType?: T;
      };
  isSampleContent?: T;
  blockStyles?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  scheme?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  subheading?: T;
  featureChip?: T;
  media?: T;
  poster?: T;
  mediaSide?: T;
  textAlign?: T;
  verticalAlign?: T;
  overlay?: T;
  minHeight?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  floatingCards?:
    | T
    | {
        title?: T;
        subtitle?: T;
        corner?: T;
        id?: T;
      };
  backgroundImage?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock_select".
 */
export interface ProductGridBlockSelect<T extends boolean = true> {
  variant?: T;
  columns?: T;
  eyebrow?: T;
  heading?: T;
  source?: T;
  category?: T;
  products?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  images?: T;
  columns?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock_select".
 */
export interface CTABannerBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock_select".
 */
export interface NewsletterSignupBlockSelect<T extends boolean = true> {
  heading?: T;
  placeholder?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitHeroBlock_select".
 */
export interface SplitHeroBlockSelect<T extends boolean = true> {
  variant?: T;
  textAlign?: T;
  overlayVerticalAlign?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  media?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  variant?: T;
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  columns?: T;
  items?:
    | T
    | {
        icon?: T;
        heading?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  numbered?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock_select".
 */
export interface LogoStripBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  grayscale?: T;
  logos?:
    | T
    | {
        image?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  provider?: T;
  url?: T;
  poster?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  address?: T;
  hours?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  phone?: T;
  whatsapp?: T;
  email?: T;
  mapEmbedUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductBlock_select".
 */
export interface FeaturedProductBlockSelect<T extends boolean = true> {
  variant?: T;
  product?: T;
  headingOverride?: T;
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IncentivesBlock_select".
 */
export interface IncentivesBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?: T;
  items?:
    | T
    | {
        icon?: T;
        heading?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryPreviewsBlock_select".
 */
export interface CategoryPreviewsBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  source?: T;
  categories?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoSectionBlock_select".
 */
export interface PromoSectionBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  media?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock_select".
 */
export interface ReviewsBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  items?:
    | T
    | {
        rating?: T;
        quote?: T;
        author?: T;
        role?: T;
        product?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaHeroBlock_select".
 */
export interface MediaHeroBlockSelect<T extends boolean = true> {
  variant?: T;
  media?: T;
  poster?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  textAlign?: T;
  verticalAlign?: T;
  overlay?: T;
  minHeight?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TickerBlock_select".
 */
export interface TickerBlockSelect<T extends boolean = true> {
  variant?: T;
  separator?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoryStatsBlock_select".
 */
export interface StoryStatsBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  image?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  contentHash?: T;
  alt?: T;
  isSampleContent?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  storeName?: T;
  currency?: T;
  logo?: T;
  description?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        backgroundColor?: T;
        textColor?: T;
        fontFamily?: T;
        fontFamilyAxes?: T;
        headingFont?: T;
        headingFontAxes?: T;
        displayFont?: T;
        displayFontAxes?: T;
        headingWeight?: T;
        bodyWeight?: T;
        buttonRadius?: T;
      };
  themeCustomizations?: T;
  blockStyleDefaults?: T;
  customCss?: T;
  customCssEnabled?: T;
  announcement?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerLayout?: T;
  logoSize?: T;
  fulfillment?:
    | T
    | {
        enabled?: T;
        timezone?: T;
        cutoffTime?: T;
        maxDaysAhead?: T;
        pickup?:
          | T
          | {
              enabled?: T;
              locationLabel?: T;
              windows?:
                | T
                | {
                    label?: T;
                    start?: T;
                    end?: T;
                    id?: T;
                  };
            };
        delivery?:
          | T
          | {
              enabled?: T;
              zones?:
                | T
                | {
                    name?: T;
                    areasNote?: T;
                    fee?: T;
                    id?: T;
                  };
              windows?:
                | T
                | {
                    label?: T;
                    start?: T;
                    end?: T;
                    id?: T;
                  };
            };
      };
  tax?:
    | T
    | {
        enabled?: T;
        registrationNumber?: T;
        rate?: T;
        pricesIncludeTax?: T;
      };
  nextInvoiceNumber?: T;
  analytics?:
    | T
    | {
        ga4MeasurementId?: T;
        gtmContainerId?: T;
        metaPixelId?: T;
        tiktokPixelId?: T;
        pinterestTagId?: T;
        snapchatPixelId?: T;
        googleAdsId?: T;
        clarityProjectId?: T;
        hotjarId?: T;
      };
  storefrontTheme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-definitions_select".
 */
export interface SectionDefinitionsSelect<T extends boolean = true> {
  name?: T;
  recipe?: T;
  presetId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-items_select".
 */
export interface ImportItemsSelect<T extends boolean = true> {
  job?: T;
  externalId?: T;
  mapped?: T;
  status?: T;
  warnings?: T;
  claimedAt?: T;
  error?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gateway-configs_select".
 */
export interface GatewayConfigsSelect<T extends boolean = true> {
  provider?: T;
  enabled?: T;
  environment?: T;
  encryptedCredentials?: T;
  configurationVersion?: T;
  publishableKey?: T;
  secretKey?: T;
  webhookSecret?: T;
  active?: T;
  webhookUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts_select".
 */
export interface PaymentAttemptsSelect<T extends boolean = true> {
  order?: T;
  provider?: T;
  providerSessionId?: T;
  idempotencyKey?: T;
  status?: T;
  amount?: T;
  currency?: T;
  providerPaymentId?: T;
  failureCode?: T;
  failureMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processed-webhook-events_select".
 */
export interface ProcessedWebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  providerEventId?: T;
  paymentAttempt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-gateway-requests_select".
 */
export interface PaymentGatewayRequestsSelect<T extends boolean = true> {
  providerName?: T;
  note?: T;
  requestedByEmail?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  products?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  orders?:
    | T
    | {
        find?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        listBlocks?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}